"""'Categories' SQLAlchemy model"""

from JDISCTF.app import DB
from sqlalchemy import ForeignKey, UniqueConstraint


class Category(DB.Model):
    """
    Category model

    A category groups challenges together under a common theme (programming, web, etc).
    A category is associated to a single event and should have a unique name within that event
    (events A and B can both have a category C, but event A cannot have two categories C).

    Attributes
    ----------
    id : int
        The unique ID of the category. Should be generated by the database. Used as primary key.

    event_id : int
        The ID of the event the category belongs to. Used as foreign key.

    name : str
        The name of the category. Max 64 characters.
    """
    id = DB.Column(DB.Integer, primary_key=True)
    __tablename__ = 'Categories'

    event_id = DB.Column(DB.Integer, ForeignKey('Events.id'), nullable=True)
    name = DB.Column(DB.String(64), index=True)

    __table_args__ = (
        UniqueConstraint('event_id', 'name', name='_event_name_uc'),
    )

    def __repr__(self):
        return '<Category id:{} event_id:{} name:{}'.format(self.id, self.event_id, self.name)
