"""Events' SQLAlchemy model"""
from sqlalchemy.ext.associationproxy import association_proxy
from sqlalchemy.orm import relationship

from JDISCTF.app import DB


class Event(DB.Model):
    """
    Event model

    The core of the application. An event's only defining characteristic is its name, which must be
    unique (i.e. 'CS Games 2019', 'United CTF 2019', etc). The rest is all handled by relations with
    the application's other models.
    """

    __tablename__ = 'Events'

    id = DB.Column(DB.Integer, primary_key=True)
    """The unique ID of the event. Should be generated by the database. Used as primary key."""
    name = DB.Column(DB.String(64), index=True, unique=True)
    """The name of the event. Max 64 characters."""
    front_page = DB.Column(DB.Text())
    """The front page content of the event. Markdown text that will be parsed by frontend"""
    teams = DB.Column(DB.Boolean)
    """Whether participants have to register as teams or individually."""

    event_administrators = relationship('EventAdministrator', back_populates='event')
    administrators = association_proxy('event_administrators', 'administrator')

    def __repr__(self):
        return '<Event id:{} name:{} teams: {}>'.format(self.id, self.name, self.teams)
