"""'Teams' SQLAlchemy model"""

from sqlalchemy import ForeignKey, UniqueConstraint
from JDISCTF.app import DB


class Team(DB.Model):
    """
    Team model

    A team is a grouping of participants who compete together. A team must always have at least one
    member.
    """

    __tablename__ = 'Teams'

    id = DB.Column(DB.Integer, primary_key=True)
    """The unique ID of the team. Should be generated by the database. Used as primary key."""
    event_id = DB.Column(DB.Integer, ForeignKey('Events.id'), nullable=True)
    """The ID of the event the team is registered to. Used as foreign key."""
    name = DB.Column(DB.String(64))
    """The name of the team. Two teams competing in the same event cannot have the same name."""

    __table_args__ = (
        UniqueConstraint('event_id', 'name', name='teams_event_name_uc'),
    )

    def __repr__(self):
        return '<Team id:{} event_id:{} name:{}'\
            .format(self.id, self.event_id, self.name)
