"""'User' SQLAlchemy model"""

from __future__ import annotations
from JDISCTF.app import DB, LOGIN_MANAGER
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(UserMixin, DB.Model):
    """
    User model

    A user of the application (event participant). A user is only represented by its username and
    authenticates on the platform with its email and password.

    Attributes
    ----------
    id : int
        The unique ID of the user. Should be generated by the database. Used as primary key.

    email : str
        The user's email. Unique. Max 255 characters.

    username : str
        The user's display name. Unique. Max 64 characters.

    password_hash : str
        The hash of the user's password. Should always be set with the 'set_password' method. Max
        128 characters.

    """
    id = DB.Column(DB.Integer, primary_key=True)
    __tablename__ = 'Users'

    email = DB.Column(DB.String(255), index=True, unique=True)
    username = DB.Column(DB.String(64), index=True, unique=True)
    password_hash = DB.Column(DB.String(128))

    def __repr__(self):
        return '<User id:{} email:{} username:{}>'.format(self.id, self.email, self.username)

    def set_password(self, password: str):
        """Hash and set the user's password"""
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str) -> bool:
        """Check whether or not this is the user's password"""
        return check_password_hash(self.password_hash, password)


@LOGIN_MANAGER.user_loader
def load_user(user_id: str) -> User:
    """Returns a User class from a user id. Required by flask-login"""
    return User.query.get(int(user_id))
