"""Added flags, teams and submissions tables

Revision ID: 0159cc2d8db7
Revises: f2f134dce486
Create Date: 2019-10-24 17:57:51.327046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0159cc2d8db7'
down_revision = 'f2f134dce486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='teams_event_name_uc')
    )
    op.create_table('Flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['Challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=True),
    sa.Column('input', sa.String(length=64), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['Challenges.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['Teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('categories_event_name_uc', 'Categories', ['event_id', 'name'])
    op.drop_constraint('_event_name_uc', 'Categories', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_event_name_uc', 'Categories', ['event_id', 'name'])
    op.drop_constraint('categories_event_name_uc', 'Categories', type_='unique')
    op.drop_table('Submissions')
    op.drop_table('Flags')
    op.drop_table('Teams')
    # ### end Alembic commands ###
