"""User email and username not unique

Revision ID: 1e08c4ac0ff8
Revises: 22d3417b85d4
Create Date: 2019-11-21 13:38:29.519688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e08c4ac0ff8'
down_revision = '22d3417b85d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Users_email', table_name='Users')
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=False)
    op.drop_index('ix_Users_username', table_name='Users')
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.create_index('ix_Users_username', 'Users', ['username'], unique=True)
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.create_index('ix_Users_email', 'Users', ['email'], unique=True)
    # ### end Alembic commands ###
