"""Updated teams, added teamMembers and teamRequests

Revision ID: 80751781e230
Revises: 0159cc2d8db7
Create Date: 2019-11-16 12:31:28.091762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80751781e230'
down_revision = '0159cc2d8db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TeamMembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('captain', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TeamRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Teams_name'), 'Teams', ['name'], unique=False)
    op.create_unique_constraint('team_event_name_uc', 'Teams', ['event_id', 'name'])
    op.drop_constraint('teams_event_name_uc', 'Teams', type_='unique')
    op.add_column('Users', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Users', 'Events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'event_id')
    op.create_unique_constraint('teams_event_name_uc', 'Teams', ['event_id', 'name'])
    op.drop_constraint('team_event_name_uc', 'Teams', type_='unique')
    op.drop_index(op.f('ix_Teams_name'), table_name='Teams')
    op.drop_table('TeamRequests')
    op.drop_table('TeamMembers')
    # ### end Alembic commands ###
