"""Events, categories and challenges

Revision ID: 85f5118d7d9d
Revises: 8dac73be3ac9
Create Date: 2019-10-02 21:53:51.033511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f5118d7d9d'
down_revision = '8dac73be3ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('front_page', sa.Text(), nullable=False),
    sa.Column('teams', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Events_name'), 'Events', ['name'], unique=True)
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Categories_name'), 'Categories', ['name'], unique=True)
    op.create_table('Challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Challenges_name'), 'Challenges', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Challenges_name'), table_name='Challenges')
    op.drop_table('Challenges')
    op.drop_index(op.f('ix_Categories_name'), table_name='Categories')
    op.drop_table('Categories')
    op.drop_index(op.f('ix_Events_name'), table_name='Events')
    op.drop_table('Events')
    # ### end Alembic commands ###
