"""Added Teams, TeamMembers, TeamRequests and event_id on user

Revision ID: a7286b1adcdc
Revises: f2f134dce486
Create Date: 2019-10-28 13:59:40.053181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7286b1adcdc'
down_revision = 'f2f134dce486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['Events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'name', name='team_event_name_uc')
    )
    op.create_index(op.f('ix_Teams_name'), 'Teams', ['name'], unique=False)
    op.create_table('TeamMembers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('captain', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TeamRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('category_event_name_uc', 'Categories', ['event_id', 'name'])
    op.drop_constraint('_event_name_uc', 'Categories', type_='unique')
    op.add_column('Users', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Users', 'Events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'event_id')
    op.create_unique_constraint('_event_name_uc', 'Categories', ['event_id', 'name'])
    op.drop_constraint('category_event_name_uc', 'Categories', type_='unique')
    op.drop_table('TeamRequests')
    op.drop_table('TeamMembers')
    op.drop_index(op.f('ix_Teams_name'), table_name='Teams')
    op.drop_table('Teams')
    # ### end Alembic commands ###
